language: node_js
node_js: stable

cache:
  directories:
    - node_modules

branches:
  only:
    - dev

before_install:
  - git config --global user.name "Alex Shalynin"
  - git config --global user.email "6602362+vishes-shell@users.noreply.github.com"
  - npm install -g hexo-cli

install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://${GH_TOKEN}@github.com/vishes-shell/vishes-shell.github.io.git master
