sudo: false
language: node_js
node_js:
  - 10

cache: npm
branches:
  only:
    - dev

before_install:
  - npm install -g hexo-cli

install:
  - npm install

before_script:
  - git config --global user.name "Alex Shalynin"
  - git config --global user.email "6602362+vishes-shell@users.noreply.github.com"

script:
  - hexo generate

after_success:
  - sed -i'' - sed -i'' "s~git@github.com:vishes-shell/vishes-shell.github.io.git~https://${GH_TOKEN}@github.com/vishes-shell/vishes-shell.github.io.git~" _config.yml
  - hexo d
